apiVersion: v1
kind: Namespace
metadata:
  name: development
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
  namespace: development
  labels:
    app: taskmanager-app
spec:
  # replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 1
  selector:
    matchLabels:
      app: taskmanager-app
  template:
    metadata:
      labels:
        app: taskmanager-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: taskmanager-app
        image: oluchioraekwe/taskmanager:latest
        imagePullPolicy: "Always"
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            cpu: "200m"
        ports:
        - containerPort: 4500
        env:
        - name: PORT
          value: "4500"
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager
  namespace: development
spec:
  selector:
    app: taskmanager-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4500
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myingress
  namespace: development
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: taskmanager
            port: 
              number: 80
