name: Buid and Deploy Resources to Docker Hub

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: The image tag
        default: latest
  push:
    branches:
      - main
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push latest
        if: ${{ !github.event.inputs.tag}}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: oluchioraekwe/taskmanager:latest

      - name: Build and push tag
        if: ${{ github.event.inputs.tag}}
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: oluchioraekwe/studentservice:${{ github.event.inputs.tag}}

  deploy-to-aks:
    needs: docker
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: k8sconfig
    
    steps:
      - name: Check out to repo
        uses: actions/checkout@v2

      - name: Deploy to Production
        run: |
          cd k8sconfig
          echo "Deploying to aks cluster..."
    